### ISSUE TITLE
Invalid header protection value

### ISSUE THREAD

**Issue by xpepermint** [syncsynchalt/illustrated-quic#3]
If my math is correct, I think that the encoded packet header byte on the last frame (UDP Datagram 8 - Close connection) at [https://quic.xargs.org/#server-application-packet-2] is incorrect. Packet header byte `54` should be `44`.

**Comment by syncsynchalt** [comment]
Hi Kristijan!

If I'm looking at the right thing, I think it's correct at `54`.  The mask that is calculated for that byte is `0xf4`:

```
... snip ...
echo $sample | xxd -r -p | openssl aes-128-ecb -K $key | head -c 5 | xxd -p

f494fdfbb6
```
Of that byte, only the lower five bits are used, changing the `0xf4` into `0x14`.  The unprotected value is `0x40`. `0x40 ^ 0x14` is `0x54`. (edit: fixed a `1f` thinko, made it `14` as it should be)

To confirm I also have the original packet capture from the connection [here](https://github.com/syncsynchalt/illustrated-quic/blob/main/captures/capture.pcap).  That shows a `0x54` byte at that location:
<img width="749" alt="Screen Shot 2022-11-29 at 9 52 38 AM" src="https://user-images.githubusercontent.com/950417/204593817-c946e0a9-12dd-4fd7-b92d-9e4bb4e8e0de.png">

Let me know if I've missed something!

**Comment by xpepermint** [comment]
Eh, my mistake. I converted the byte useing the last 4 bits not 5 bits. Sorry for that. Thx
